import type { Floor, FurnitureItem, Project, Settings } from "../types";
import { rect } from "./geometry";

/*
 * The apartment as traced from the builder's marketing floorplan. The only
 * dimensions printed on it are the room labels (Bedroom 1 12'x11', Living
 * 13'x12', Den 9'x9', Bedroom 2 14'x13'); everything else is scaled from the
 * drawing at roughly 20 px per foot and should be verified on site with a tape.
 * Walls are 6" thick; rooms are drawn to their inside faces. The building's
 * top-right corner is recessed on both floors: a porch in front of the entry
 * downstairs and the living-room patio above it. Bath 1 is an en-suite off
 * Bedroom 1.
 */

export const OUTSIDE = "outside";

const first: Floor = {
  id: "first",
  name: "First floor",
  width: 258,
  height: 480,
  rooms: [
    { id: "bed1", name: "Bedroom 1", polygon: rect(6, 6, 144, 132) },
    { id: "closet1", name: "Walk-in closet", polygon: rect(6, 144, 56, 60) },
    { id: "bath1", name: "Bath 1", polygon: rect(68, 144, 82, 60) },
    {
      id: "entry",
      name: "Entry",
      // The front door is set back 27" under a porch.
      polygon: rect(156, 33, 96, 171),
    },
    { id: "garage", name: "2-car garage", polygon: rect(6, 210, 246, 264), excludeFromArea: true },
    { id: "porch", name: "Porch", polygon: rect(158, 3, 94, 24), excludeFromArea: true, outdoor: true },
  ],
  fixtures: [
    { id: "stairs1", name: "Stairs up", polygon: rect(204, 66, 48, 96) },
    { id: "storage1", name: "Storage", polygon: rect(204, 168, 48, 36) },
    { id: "wh", name: "Water heater", polygon: rect(6, 210, 24, 24) },
    { id: "wd", name: "W/D", polygon: rect(36, 210, 30, 30) },
    { id: "gshelf", name: "Shelf", polygon: rect(72, 210, 60, 16) },
    { id: "vanity1", name: "Vanity", polygon: rect(68, 144, 22, 24) },
    { id: "toilet1", name: "Toilet", polygon: rect(68, 176, 20, 28) },
    { id: "tub1", name: "Tub", polygon: rect(120, 144, 30, 60) },
  ],
  windows: [
    { id: "w1-bed", name: "Bedroom 1 window", a: { x: 3, y: 36 }, b: { x: 3, y: 114 } },
    { id: "w1-stair", name: "Stairwell window", a: { x: 255, y: 78 }, b: { x: 255, y: 126 }, sill: 42 },
  ],
  passages: [
    {
      id: "front-door",
      name: "Front door",
      kind: "exterior",
      floorId: "first",
      a: { x: 180, y: 30 },
      b: { x: 216, y: 30 },
      width: 36,
      height: 80,
      rooms: ["porch", "entry"],
      swingInto: "entry",
      hinge: "a",
    },
    {
      id: "porch-steps",
      name: "Porch",
      kind: "opening",
      floorId: "first",
      a: { x: 158, y: 3 },
      b: { x: 252, y: 3 },
      width: 94,
      rooms: [OUTSIDE, "porch"],
    },
    {
      id: "bed1-door",
      name: "Bedroom 1 door",
      kind: "door",
      floorId: "first",
      a: { x: 153, y: 60 },
      b: { x: 153, y: 90 },
      width: 30,
      height: 80,
      rooms: ["entry", "bed1"],
      swingInto: "bed1",
      hinge: "a",
    },
    {
      id: "bath1-door",
      name: "Bath 1 door",
      kind: "door",
      floorId: "first",
      a: { x: 90, y: 141 },
      b: { x: 120, y: 141 },
      width: 30,
      height: 80,
      rooms: ["bed1", "bath1"],
      swingInto: "bath1",
      hinge: "a",
    },
    {
      id: "closet1-door",
      name: "Closet 1 door",
      kind: "door",
      floorId: "first",
      a: { x: 20, y: 141 },
      b: { x: 50, y: 141 },
      width: 30,
      height: 80,
      rooms: ["bed1", "closet1"],
      swingInto: "closet1",
      hinge: "a",
    },
    {
      id: "garage-door",
      name: "Garage entry door",
      kind: "door",
      floorId: "first",
      a: { x: 162, y: 207 },
      b: { x: 194, y: 207 },
      width: 32,
      height: 80,
      rooms: ["entry", "garage"],
      swingInto: "entry",
      hinge: "a",
    },
    {
      id: "garage-overhead",
      name: "Garage overhead door",
      kind: "exterior",
      floorId: "first",
      a: { x: 30, y: 477 },
      b: { x: 222, y: 477 },
      width: 192,
      height: 84,
      rooms: [OUTSIDE, "garage"],
    },
    {
      id: "stairs",
      name: "Stairs",
      kind: "stair",
      floorId: "first",
      a: { x: 228, y: 162 },
      b: { x: 228, y: 66 },
      width: 36,
      rooms: ["entry", "living"],
      // A straight run: you step on at the north end downstairs and off at the
      // south end upstairs. No landing turn, so only width and headroom limit
      // what can be carried up.
      stair: { width: 42, headroom: 80, landingA: { x: 196, y: 84 }, landingB: { x: 186, y: 205 } },
    },
  ],
};

const second: Floor = {
  id: "second",
  name: "Second floor",
  width: 300,
  height: 480,
  rooms: [
    {
      id: "living",
      name: "Living",
      polygon: [
        { x: 6, y: 6 },
        { x: 152, y: 6 },
        { x: 152, y: 42 },
        { x: 252, y: 42 },
        { x: 252, y: 138 },
        { x: 6, y: 138 },
      ],
    },
    { id: "kitchen", name: "Kitchen", polygon: rect(6, 138, 135, 133) },
    {
      id: "hall",
      name: "Stair landing",
      polygon: [
        { x: 141, y: 138 },
        { x: 172, y: 138 },
        { x: 172, y: 170 },
        { x: 201, y: 170 },
        { x: 201, y: 222 },
        { x: 141, y: 222 },
      ],
    },
    { id: "den", name: "Den / dining", polygon: rect(146, 228, 106, 98) },
    { id: "hall2", name: "Bedroom hall", polygon: rect(65, 271, 76, 53) },
    {
      id: "bath2",
      name: "Bath 2",
      polygon: [
        { x: 6, y: 277 },
        { x: 59, y: 277 },
        { x: 59, y: 330 },
        { x: 97, y: 330 },
        { x: 97, y: 390 },
        { x: 6, y: 390 },
      ],
    },
    { id: "closet2", name: "Walk-in closet", polygon: rect(6, 396, 91, 78) },
    { id: "bed2", name: "Bedroom 2", polygon: rect(103, 330, 149, 144) },
    { id: "patioA", name: "Patio", polygon: rect(158, 6, 68, 30), excludeFromArea: true, outdoor: true },
    { id: "patioB", name: "Patio", polygon: rect(258, 236, 34, 81), excludeFromArea: true, outdoor: true },
  ],
  fixtures: [
    {
      id: "stairs2",
      name: "Stairs down",
      // Treads on the right, open stairwell with a rail on the left.
      polygon: [
        { x: 172, y: 85 },
        { x: 252, y: 85 },
        { x: 252, y: 222 },
        { x: 201, y: 222 },
        { x: 201, y: 170 },
        { x: 172, y: 170 },
      ],
    },
    { id: "pantry", name: "Pantry", polygon: rect(6, 141, 22, 35) },
    { id: "counter-l", name: "Range / counter", polygon: rect(6, 176, 22, 95) },
    { id: "island", name: "Island", polygon: rect(68, 146, 41, 58) },
    { id: "counter-b", name: "Counter", polygon: rect(28, 251, 40, 20) },
    { id: "fridge", name: "Fridge", polygon: rect(68, 251, 28, 20) },
    { id: "vanity2", name: "Vanity", polygon: rect(6, 300, 24, 30) },
    { id: "toilet2", name: "Toilet", polygon: rect(8, 349, 18, 26) },
    { id: "tub2", name: "Tub", polygon: rect(66, 330, 30, 60) },
    { id: "linen2", name: "Linen", polygon: rect(60, 396, 20, 16) },
  ],
  windows: [
    { id: "w2-living-top", name: "Living window", a: { x: 36, y: 3 }, b: { x: 146, y: 3 } },
    { id: "w2-living-left", name: "Living side window", a: { x: 3, y: 57 }, b: { x: 3, y: 126 } },
    { id: "w2-stair", name: "Stairwell window", a: { x: 255, y: 97 }, b: { x: 255, y: 117 }, sill: 42 },
    { id: "w2-bed-right", name: "Bedroom 2 side window", a: { x: 255, y: 338 }, b: { x: 255, y: 362 } },
    { id: "w2-bed-a", name: "Bedroom 2 window", a: { x: 132, y: 477 }, b: { x: 164, y: 477 } },
    { id: "w2-bed-b", name: "Bedroom 2 window", a: { x: 193, y: 477 }, b: { x: 233, y: 477 } },
  ],
  passages: [
    { id: "living-kitchen", name: "Living ↔ kitchen", kind: "opening", floorId: "second", a: { x: 6, y: 138 }, b: { x: 141, y: 138 }, width: 135, rooms: ["living", "kitchen"] },
    { id: "living-hall", name: "Living ↔ stair landing", kind: "opening", floorId: "second", a: { x: 141, y: 138 }, b: { x: 172, y: 138 }, width: 31, rooms: ["living", "hall"] },
    { id: "kitchen-hall", name: "Kitchen ↔ stair landing", kind: "opening", floorId: "second", a: { x: 141, y: 138 }, b: { x: 141, y: 222 }, width: 84, rooms: ["kitchen", "hall"] },
    { id: "hall-den", name: "Stair landing ↔ den", kind: "opening", floorId: "second", a: { x: 146, y: 225 }, b: { x: 201, y: 225 }, width: 55, rooms: ["hall", "den"] },
    { id: "kitchen-den", name: "Kitchen ↔ den", kind: "opening", floorId: "second", a: { x: 143.5, y: 228 }, b: { x: 143.5, y: 251 }, width: 23, rooms: ["kitchen", "den"] },
    { id: "kitchen-hall2", name: "Kitchen ↔ bedroom hall", kind: "opening", floorId: "second", a: { x: 96, y: 271 }, b: { x: 141, y: 271 }, width: 45, rooms: ["kitchen", "hall2"] },
    {
      id: "bath2-door",
      name: "Bath 2 door",
      kind: "door",
      floorId: "second",
      a: { x: 62, y: 283 },
      b: { x: 62, y: 313 },
      width: 30,
      height: 80,
      rooms: ["hall2", "bath2"],
      swingInto: "bath2",
      hinge: "a",
    },
    {
      id: "bed2-door",
      name: "Bedroom 2 door",
      kind: "door",
      floorId: "second",
      a: { x: 106, y: 327 },
      b: { x: 136, y: 327 },
      width: 30,
      height: 80,
      rooms: ["hall2", "bed2"],
      swingInto: "bed2",
      hinge: "a",
    },
    {
      id: "closet2-door",
      name: "Closet 2 door",
      kind: "door",
      floorId: "second",
      a: { x: 100, y: 410 },
      b: { x: 100, y: 440 },
      width: 30,
      height: 80,
      rooms: ["bed2", "closet2"],
      swingInto: "closet2",
      hinge: "a",
    },
    {
      id: "patioA-door",
      name: "Living patio door",
      kind: "exterior",
      floorId: "second",
      a: { x: 173, y: 39 },
      b: { x: 209, y: 39 },
      width: 36,
      height: 80,
      rooms: ["living", "patioA"],
      swingInto: "living",
      hinge: "a",
    },
    {
      id: "patioB-door",
      name: "Den patio door",
      kind: "exterior",
      floorId: "second",
      a: { x: 255, y: 256 },
      b: { x: 255, y: 292 },
      width: 36,
      height: 80,
      rooms: ["den", "patioB"],
      swingInto: "den",
      hinge: "a",
    },
  ],
};

export const defaultSettings: Settings = {
  mainPathWidth: 36,
  secondaryPathWidth: 24,
  drawerClearance: 18,
  bedSideClearance: 24,
  bedBothSides: true,
  transportTolerance: 1,
  defaultDoorHeight: 80,
  snap: 1,
  cellSize: 2,
  furnitureGap: 0,
  tableClearance: 36,
  defaultSillHeight: 30,
  targetSqFt: 1219,
};

// From the measuring sheet: depth x width x height, inches.
export const defaultFurniture: FurnitureItem[] = [
  { id: "m-bed", name: "Bed", set: "Main bedroom", kind: "bed", d: 96, w: 80, h: 53, quantity: 1, disassembles: true },
  { id: "m-night", name: "Nightstand", set: "Main bedroom", kind: "nightstand", d: 18, w: 24, h: 26, quantity: 2, allowInBedZone: true },
  { id: "m-dresser", name: "Dresser", set: "Main bedroom", kind: "dresser", d: 20, w: 36, h: 48, quantity: 1 },
  { id: "m-chest", name: "Chest of drawers", set: "Main bedroom", kind: "chest", d: 21, w: 62, h: 37.5, quantity: 1 },
  { id: "m-gent", name: "Gentleman's chest", set: "Main bedroom", kind: "chest", d: 20, w: 48, h: 68, quantity: 1 },
  { id: "m-dresser-old", name: "Dresser (old)", set: "Main bedroom", kind: "dresser", d: 18, w: 40, h: 50, quantity: 1 },
  { id: "m-gent-old", name: "Gentleman's chest (old)", set: "Main bedroom", kind: "chest", d: 19.5, w: 50, h: 52, quantity: 1 },
  { id: "z-bed", name: "Bed", set: "Zara", kind: "bed", d: 86, w: 64, h: 60, quantity: 1, disassembles: true },
  { id: "z-night", name: "Nightstand", set: "Zara", kind: "nightstand", d: 20.5, w: 23.5, h: 25, quantity: 2, allowInBedZone: true },
  { id: "z-dresser", name: "Dresser", set: "Zara", kind: "dresser", d: 20.5, w: 54, h: 34, quantity: 1 },
  { id: "z-shelf", name: "Shelf", set: "Zara", kind: "shelf", d: 16, w: 34, h: 56.5, quantity: 1 },
  { id: "s-glass", name: "Shelf (glass)", set: "Shelves", kind: "shelf", d: 15, w: 47.5, h: 47.5, quantity: 2 },
  { id: "s-plain", name: "Shelf (plain)", set: "Shelves", kind: "shelf", d: 15, w: 32, h: 47.5, quantity: 4 },
  { id: "s-curves", name: "Shelf (curves)", set: "Shelves", kind: "shelf", d: 16, w: 36, h: 74, quantity: 1 },
  { id: "d-table", name: "Table", set: "Dining", kind: "table", d: 73.5, w: 45, h: 30, quantity: 1 },
  { id: "d-china", name: "China cabinet", set: "Dining", kind: "cabinet", d: 17.5, w: 39, h: 80, quantity: 1 },
  { id: "d-side", name: "Sideboard", set: "Dining", kind: "cabinet", d: 20, w: 72, h: 42, quantity: 1 },
  // Yamaha U3 upright: 131 cm tall, 153 cm wide, 65 cm deep, about 240 kg.
  { id: "piano", name: "Piano (Yamaha U3)", set: "Living", kind: "piano", d: 25.5, w: 60, h: 51.5, quantity: 1, keepUpright: true, notes: "About 530 lb. Keep off exterior walls and away from windows and vents if you can." },
];

export function defaultProject(): Project {
  return structuredClone({
    version: 1 as const,
    name: "New apartment",
    floors: [first, second],
    furniture: defaultFurniture,
    placements: [],
    settings: defaultSettings,
    activeFloorId: "first",
  });
}
