import type { Floor, FurnitureItem, Project, Settings } from "../types";
import { rect } from "./geometry";

/*
 * The apartment as traced from the builder's marketing floorplan. The only
 * dimensions printed on it are the room labels (Bedroom 1 12'x11', Living
 * 13'x12', Den 9'x9', Bedroom 2 14'x13'); everything else is scaled from the
 * drawing at roughly 20 px per foot and should be verified on site with a tape.
 * Walls are 6" thick; rooms are drawn to their inside faces. The first floor's
 * front entry is recessed under a porch, Bath 1 is an en-suite off Bedroom 1,
 * and the stairwell's outer wall steps in beside the stairs.
 */

export const OUTSIDE = "outside";

const first: Floor = {
  id: "first",
  name: "First floor",
  width: 258,
  height: 480,
  rooms: [
    { id: "bed1", name: "Bedroom 1", polygon: rect(6, 6, 144, 132) },
    { id: "closet1", name: "Walk-in closet", polygon: rect(6, 144, 56, 60) },
    { id: "bath1", name: "Bath 1", polygon: rect(68, 144, 82, 60) },
    {
      id: "entry",
      name: "Entry",
      // The front door is set back under a porch (27" deep) and the stairwell's
      // outer wall steps in 6" beside the stairs.
      polygon: [
        { x: 156, y: 33 },
        { x: 252, y: 33 },
        { x: 252, y: 72 },
        { x: 246, y: 72 },
        { x: 246, y: 126 },
        { x: 252, y: 126 },
        { x: 252, y: 204 },
        { x: 156, y: 204 },
      ],
    },
    { id: "garage", name: "2-car garage", polygon: rect(6, 210, 246, 264) },
  ],
  fixtures: [
    {
      id: "stairs1",
      name: "Stairs up",
      polygon: [
        { x: 204, y: 66 },
        { x: 252, y: 66 },
        { x: 252, y: 72 },
        { x: 246, y: 72 },
        { x: 246, y: 126 },
        { x: 252, y: 126 },
        { x: 252, y: 162 },
        { x: 204, y: 162 },
      ],
    },
    { id: "storage1", name: "Storage", polygon: rect(204, 168, 48, 36) },
    { id: "wh", name: "Water heater", polygon: rect(6, 210, 24, 24) },
    { id: "wd", name: "W/D", polygon: rect(36, 210, 30, 30) },
    { id: "gshelf", name: "Shelf", polygon: rect(72, 210, 60, 16) },
    { id: "vanity1", name: "Vanity", polygon: rect(68, 144, 22, 24) },
    { id: "toilet1", name: "Toilet", polygon: rect(68, 176, 20, 28) },
    { id: "tub1", name: "Tub", polygon: rect(120, 144, 30, 60) },
  ],
  passages: [
    {
      id: "front-door",
      name: "Front door",
      kind: "exterior",
      floorId: "first",
      a: { x: 180, y: 30 },
      b: { x: 216, y: 30 },
      width: 36,
      height: 80,
      rooms: [OUTSIDE, "entry"],
      swingInto: "entry",
      hinge: "a",
    },
    {
      id: "bed1-door",
      name: "Bedroom 1 door",
      kind: "door",
      floorId: "first",
      a: { x: 153, y: 60 },
      b: { x: 153, y: 90 },
      width: 30,
      height: 80,
      rooms: ["entry", "bed1"],
      swingInto: "bed1",
      hinge: "a",
    },
    {
      id: "bath1-door",
      name: "Bath 1 door",
      kind: "door",
      floorId: "first",
      a: { x: 90, y: 141 },
      b: { x: 120, y: 141 },
      width: 30,
      height: 80,
      rooms: ["bed1", "bath1"],
      swingInto: "bath1",
      hinge: "a",
    },
    {
      id: "closet1-door",
      name: "Closet 1 door",
      kind: "door",
      floorId: "first",
      a: { x: 20, y: 141 },
      b: { x: 50, y: 141 },
      width: 30,
      height: 80,
      rooms: ["bed1", "closet1"],
      swingInto: "closet1",
      hinge: "a",
    },
    {
      id: "garage-door",
      name: "Garage entry door",
      kind: "door",
      floorId: "first",
      a: { x: 162, y: 207 },
      b: { x: 194, y: 207 },
      width: 32,
      height: 80,
      rooms: ["entry", "garage"],
      swingInto: "entry",
      hinge: "a",
    },
    {
      id: "garage-overhead",
      name: "Garage overhead door",
      kind: "exterior",
      floorId: "first",
      a: { x: 30, y: 477 },
      b: { x: 222, y: 477 },
      width: 192,
      height: 84,
      rooms: [OUTSIDE, "garage"],
    },
    {
      id: "stairs",
      name: "Stairs",
      kind: "stair",
      floorId: "first",
      a: { x: 228, y: 162 },
      b: { x: 228, y: 66 },
      width: 36,
      rooms: ["entry", "living"],
      stair: { width: 36, turn: { a: 36, b: 36 }, headroom: 80, landingA: { x: 196, y: 150 }, landingB: { x: 196, y: 180 } },
    },
  ],
};

const second: Floor = {
  id: "second",
  name: "Second floor",
  width: 306,
  height: 480,
  rooms: [
    {
      id: "living",
      name: "Living",
      polygon: [
        { x: 6, y: 6 },
        { x: 174, y: 6 },
        { x: 174, y: 33 },
        { x: 228, y: 33 },
        { x: 228, y: 6 },
        { x: 252, y: 6 },
        { x: 252, y: 141 },
        { x: 6, y: 141 },
      ],
    },
    { id: "kitchen", name: "Kitchen", polygon: rect(6, 141, 138, 135) },
    { id: "hall", name: "Hall", polygon: rect(144, 141, 108, 63) },
    { id: "den", name: "Den / dining", polygon: rect(144, 204, 108, 108) },
    { id: "hall2", name: "Bedroom hall", polygon: rect(84, 276, 54, 36) },
    { id: "bath2", name: "Bath 2", polygon: rect(6, 282, 72, 108) },
    { id: "closet2", name: "Walk-in closet", polygon: rect(6, 396, 72, 78) },
    { id: "bed2", name: "Bedroom 2", polygon: rect(84, 318, 168, 156) },
    { id: "patioA", name: "Patio", polygon: rect(174, 6, 54, 21) },
    { id: "patioB", name: "Patio", polygon: rect(258, 270, 42, 60) },
  ],
  fixtures: [
    { id: "stairs2", name: "Stairs down", polygon: rect(204, 72, 48, 126) },
    { id: "pantry", name: "Pantry", polygon: rect(6, 141, 24, 30) },
    { id: "counter-l", name: "Range / counter", polygon: rect(6, 171, 24, 105) },
    { id: "island", name: "Island", polygon: rect(60, 147, 36, 66) },
    { id: "counter-b", name: "Counter", polygon: rect(30, 246, 36, 30) },
    { id: "fridge", name: "Fridge", polygon: rect(66, 246, 30, 30) },
    { id: "vanity2", name: "Vanity", polygon: rect(6, 282, 26, 30) },
    { id: "toilet2", name: "Toilet", polygon: rect(6, 318, 20, 26) },
    { id: "tub2", name: "Tub", polygon: rect(48, 300, 30, 90) },
  ],
  passages: [
    { id: "living-kitchen", name: "Living ↔ kitchen", kind: "opening", floorId: "second", a: { x: 6, y: 141 }, b: { x: 144, y: 141 }, width: 138, rooms: ["living", "kitchen"] },
    { id: "living-hall", name: "Living ↔ hall", kind: "opening", floorId: "second", a: { x: 144, y: 141 }, b: { x: 204, y: 141 }, width: 60, rooms: ["living", "hall"] },
    { id: "kitchen-hall", name: "Kitchen ↔ hall", kind: "opening", floorId: "second", a: { x: 144, y: 141 }, b: { x: 144, y: 204 }, width: 63, rooms: ["kitchen", "hall"] },
    { id: "hall-den", name: "Hall ↔ den", kind: "opening", floorId: "second", a: { x: 144, y: 204 }, b: { x: 252, y: 204 }, width: 108, rooms: ["hall", "den"] },
    { id: "kitchen-hall2", name: "Kitchen ↔ bedroom hall", kind: "opening", floorId: "second", a: { x: 84, y: 276 }, b: { x: 138, y: 276 }, width: 54, rooms: ["kitchen", "hall2"] },
    {
      id: "bath2-door",
      name: "Bath 2 door",
      kind: "door",
      floorId: "second",
      a: { x: 81, y: 282 },
      b: { x: 81, y: 312 },
      width: 30,
      height: 80,
      rooms: ["hall2", "bath2"],
      swingInto: "bath2",
      hinge: "a",
    },
    {
      id: "bed2-door",
      name: "Bedroom 2 door",
      kind: "door",
      floorId: "second",
      a: { x: 96, y: 315 },
      b: { x: 126, y: 315 },
      width: 30,
      height: 80,
      rooms: ["hall2", "bed2"],
      swingInto: "bed2",
      hinge: "a",
    },
    {
      id: "closet2-door",
      name: "Closet 2 door",
      kind: "door",
      floorId: "second",
      a: { x: 81, y: 410 },
      b: { x: 81, y: 440 },
      width: 30,
      height: 80,
      rooms: ["bed2", "closet2"],
      swingInto: "closet2",
      hinge: "a",
    },
    {
      id: "patioA-door",
      name: "Living patio door",
      kind: "exterior",
      floorId: "second",
      a: { x: 183, y: 30 },
      b: { x: 219, y: 30 },
      width: 36,
      height: 80,
      rooms: ["living", "patioA"],
      swingInto: "living",
      hinge: "a",
    },
    {
      id: "patioB-door",
      name: "Den patio door",
      kind: "exterior",
      floorId: "second",
      a: { x: 255, y: 282 },
      b: { x: 255, y: 312 },
      width: 30,
      height: 80,
      rooms: ["den", "patioB"],
      swingInto: "den",
      hinge: "a",
    },
  ],
};

export const defaultSettings: Settings = {
  mainPathWidth: 36,
  secondaryPathWidth: 24,
  drawerClearance: 18,
  bedSideClearance: 24,
  bedBothSides: true,
  transportTolerance: 1,
  defaultDoorHeight: 80,
  snap: 1,
  cellSize: 2,
  furnitureGap: 0,
  tableClearance: 36,
};

// From the measuring sheet: depth x width x height, inches.
export const defaultFurniture: FurnitureItem[] = [
  { id: "m-bed", name: "Bed", set: "Main bedroom", kind: "bed", d: 96, w: 80, h: 53, quantity: 1, disassembles: true },
  { id: "m-night", name: "Nightstand", set: "Main bedroom", kind: "nightstand", d: 18, w: 24, h: 26, quantity: 2, allowInBedZone: true },
  { id: "m-dresser", name: "Dresser", set: "Main bedroom", kind: "dresser", d: 20, w: 36, h: 48, quantity: 1 },
  { id: "m-chest", name: "Chest of drawers", set: "Main bedroom", kind: "chest", d: 21, w: 62, h: 37.5, quantity: 1 },
  { id: "m-gent", name: "Gentleman's chest", set: "Main bedroom", kind: "chest", d: 20, w: 48, h: 68, quantity: 1 },
  { id: "m-dresser-old", name: "Dresser (old)", set: "Main bedroom", kind: "dresser", d: 18, w: 40, h: 50, quantity: 1 },
  { id: "m-gent-old", name: "Gentleman's chest (old)", set: "Main bedroom", kind: "chest", d: 19.5, w: 50, h: 52, quantity: 1 },
  { id: "z-bed", name: "Bed", set: "Zara", kind: "bed", d: 86, w: 64, h: 60, quantity: 1, disassembles: true },
  { id: "z-night", name: "Nightstand", set: "Zara", kind: "nightstand", d: 20.5, w: 23.5, h: 25, quantity: 2, allowInBedZone: true },
  { id: "z-dresser", name: "Dresser", set: "Zara", kind: "dresser", d: 20.5, w: 54, h: 34, quantity: 1 },
  { id: "z-shelf", name: "Shelf", set: "Zara", kind: "shelf", d: 16, w: 34, h: 56.5, quantity: 1 },
  { id: "s-glass", name: "Shelf (glass)", set: "Shelves", kind: "shelf", d: 15, w: 47.5, h: 47.5, quantity: 2 },
  { id: "s-plain", name: "Shelf (plain)", set: "Shelves", kind: "shelf", d: 15, w: 32, h: 47.5, quantity: 4 },
  { id: "s-curves", name: "Shelf (curves)", set: "Shelves", kind: "shelf", d: 16, w: 36, h: 74, quantity: 1 },
  { id: "d-table", name: "Table", set: "Dining", kind: "table", d: 73.5, w: 45, h: 30, quantity: 1 },
  { id: "d-china", name: "China cabinet", set: "Dining", kind: "cabinet", d: 17.5, w: 39, h: 80, quantity: 1 },
  { id: "d-side", name: "Sideboard", set: "Dining", kind: "cabinet", d: 20, w: 72, h: 42, quantity: 1 },
];

export function defaultProject(): Project {
  return structuredClone({
    version: 1 as const,
    name: "New apartment",
    floors: [first, second],
    furniture: defaultFurniture,
    placements: [],
    settings: defaultSettings,
    activeFloorId: "first",
  });
}
